import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/Header/Header";
import { SideBar } from "@/components/shared/SideBar/SideBar";
import { Footer } from "@/components/shared/Footer/Footer";
import styles from "./layout.module.css";

const inter = Noto_Sans({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "first Next.js app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <SideBar className={styles.sidebar} />
          <div className={styles.body}>{children}</div>
          <Footer className={styles.footer} />
        </div>
      </body>
    </html>
  );
}
